---

- name: Install Unattended Upgrades
  apt:
    name: ['debconf-utils', 'unattended-upgrades']
    state: present

- name: Enable Unattended Upgrades (Automatic Security Updates)
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: true
    vtype: boolean
